- hosts: localhost
  vars:
    KUBECONFIG: "{{ KUBECONFIG }}"

  tasks:
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('file', 'service.yml') }}"
      validate_certs: no
      namespace: default

  - debug:
      msg: "{{ appImage }}"

  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: python-sample
          labels:
            role: app
        spec:
          replicas: 2
          selector:
            matchLabels:
              role: app
          template:
            metadata:
              labels:
                role: app
            spec:
              containers:
              - name: app
                image: "{{ appImage }}"
                resources:
                  requests:
                    cpu: 10m
              imagePullSecrets:
              - name: docker-repo
